# Site settings
title: React Project Template
description: Project Template
url: https://neglux.github.io
baseurl: ""

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# GitHub Pages specific configuration
remote_theme: just-the-docs/just-the-docs # Replace with the GitHub username and repository name for your desired Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
# Custom configuration
# Add any additional custom configuration options here
